export const initialProjects = [
  // 01: UGC ADS
  {
    id: 'ugc-01',
    number: '01',
    title: 'GlowLab Direct UGC',
    category: 'UGC ADS',
    tagline: 'High-converting TikTok & Instagram Reels UGC campaign with 8 dynamic hook variations and creator-led storytelling.',
    col1Image1: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1000&q=85',
    col1Image2: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1000&q=85',
    col2Image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1400&q=85',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-vertical-video-of-a-woman-showing-a-product-to-the-camera-43666-large.mp4',
    mediaType: 'video',
    mediaItems: [
      {
        id: 'm-ugc1-1',
        type: 'video',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-vertical-video-of-a-woman-showing-a-product-to-the-camera-43666-large.mp4',
        poster: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1400&q=85',
        title: 'Direct Product Demo Hook',
      },
      {
        id: 'm-ugc1-2',
        type: 'video',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-girl-doing-gymnastics-exercises-in-nature-41566-large.mp4',
        poster: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1000&q=85',
        title: 'Dynamic Creator Lifestyle Reel',
      },
      {
        id: 'm-ugc1-3',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1000&q=85',
        title: 'Verified Creator Showcase',
        duration: 4,
      },
    ],
    liveUrl: 'https://instagram.com',
    aspectRatio: '9:16',
    techStack: ['9:16 Vertical', '8 Hook Variations', '4.8x ROAS', 'Direct-Response Creative'],
    featured: true,
  },
  {
    id: 'ugc-02',
    number: '02',
    title: 'Apex Fit Creator Series',
    category: 'UGC ADS',
    aspectRatio: '9:16',
    tagline: 'Viral fitness & supplement UGC creator ad package engineered for Meta and TikTok paid performance channels.',
    col1Image1: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1000&q=85',
    col1Image2: 'https://images.unsplash.com/photo-1549060279-7e168fcee0c2?auto=format&fit=crop&w=1000&q=85',
    col2Image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1400&q=85',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-girl-doing-gymnastics-exercises-in-nature-41566-large.mp4',
    mediaType: 'video',
    mediaItems: [
      {
        id: 'm-ugc2-1',
        type: 'video',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-girl-doing-gymnastics-exercises-in-nature-41566-large.mp4',
        poster: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1400&q=85',
        title: 'High-Impact Workout Reel',
      },
      {
        id: 'm-ugc2-2',
        type: 'video',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-vertical-video-of-a-woman-showing-a-product-to-the-camera-43666-large.mp4',
        poster: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1000&q=85',
        title: 'Supplement Unboxing & Taste Test',
      },
      {
        id: 'm-ugc2-3',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1549060279-7e168fcee0c2?auto=format&fit=crop&w=1000&q=85',
        title: 'Athlete Performance Stills',
        duration: 4,
      },
    ],
    liveUrl: 'https://tiktok.com',
    techStack: ['Creator Production', 'TikTok Ads', 'Meta Reels', 'Ad-Ready Exports'],
    featured: true,
  },
  {
    id: 'ugc-03',
    number: '03',
    title: 'Velox Hydration Direct UGC',
    category: 'UGC ADS',
    tagline: 'High-velocity beverage & wellness TikTok UGC with multiple creator perspectives and direct conversion hooks.',
    col1Image1: 'https://images.unsplash.com/photo-1556740758-90de374c12ad?auto=format&fit=crop&w=1000&q=85',
    col1Image2: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=1000&q=85',
    col2Image: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=1400&q=85',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-vertical-video-of-a-woman-showing-a-product-to-the-camera-43666-large.mp4',
    mediaType: 'video',
    mediaItems: [
      {
        id: 'm-ugc3-1',
        type: 'video',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-vertical-video-of-a-woman-showing-a-product-to-the-camera-43666-large.mp4',
        poster: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=1400&q=85',
        title: 'Electrolyte Dissolve Test Hook',
      },
      {
        id: 'm-ugc3-2',
        type: 'video',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-girl-doing-gymnastics-exercises-in-nature-41566-large.mp4',
        poster: 'https://images.unsplash.com/photo-1556740758-90de374c12ad?auto=format&fit=crop&w=1000&q=85',
        title: 'Morning Routine Direct Testimonial',
      },
      {
        id: 'm-ugc3-3',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=1000&q=85',
        title: 'Packaging & Ingredients Close-up',
        duration: 4,
      },
    ],
    liveUrl: 'https://tiktok.com',
    techStack: ['9:16 Creator Video', 'Meta Ad Export', 'Direct Response', 'A/B Hook Variations'],
    featured: true,
  },
  {
    id: 'ugc-04',
    number: '04',
    title: 'Lumora Beauty Creator Ads',
    category: 'UGC ADS',
    tagline: 'Viral unboxing, before/after demonstration & creator testimonial package built for TikTok Spark Ads.',
    col1Image1: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=1000&q=85',
    col1Image2: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&w=1000&q=85',
    col2Image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=1400&q=85',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-girl-doing-gymnastics-exercises-in-nature-41566-large.mp4',
    mediaType: 'video',
    mediaItems: [
      {
        id: 'm-ugc4-1',
        type: 'video',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-vertical-video-of-a-woman-showing-a-product-to-the-camera-43666-large.mp4',
        poster: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=1400&q=85',
        title: 'Skin Glow Transformation Hook',
      },
      {
        id: 'm-ugc4-2',
        type: 'video',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-girl-doing-gymnastics-exercises-in-nature-41566-large.mp4',
        poster: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=1000&q=85',
        title: 'Outdoor Clean Beauty Routine',
      },
      {
        id: 'm-ugc4-3',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&w=1000&q=85',
        title: 'Texture & Application Macro',
        duration: 4,
      },
    ],
    liveUrl: 'https://instagram.com',
    techStack: ['TikTok Spark Ads', 'Reels Hook Engine', 'Creator Network', 'UGC Scaling'],
    featured: true,
  },
  // 02: AI VIDEOS
  {
    id: 'aiv-01',
    number: '03',
    title: 'Aura Chrono AI Commercial',
    category: 'AI VIDEOS',
    tagline: 'Cinematic luxury timepiece commercial generated end-to-end with generative AI visual models and spatial audio.',
    col1Image1: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1000&q=85',
    col1Image2: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1000&q=85',
    col2Image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1400&q=85',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-circuit-board-with-glowing-signals-31910-large.mp4',
    mediaType: 'video',
    mediaItems: [
      {
        id: 'm-aiv1-1',
        type: 'video',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-circuit-board-with-glowing-signals-31910-large.mp4',
        poster: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1400&q=85',
        title: 'Neural Mechanical Core',
      },
      {
        id: 'm-aiv1-2',
        type: 'video',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-futuristic-abstract-tunnel-with-glowing-lines-41584-large.mp4',
        poster: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1000&q=85',
        title: 'Temporal Warp Sequence',
      },
      {
        id: 'm-aiv1-3',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1000&q=85',
        title: 'Watch Bezel & Sapphire Glass Polish',
        duration: 4,
      },
    ],
    liveUrl: 'https://vimeo.com',
    techStack: ['Gen-3 Visuals', '4K Master', 'Cinematic Sound Design', 'AI Commercial'],
    featured: true,
  },
  {
    id: 'aiv-02',
    number: '04',
    title: 'NeoCyber Spatial Film',
    category: 'AI VIDEOS',
    tagline: 'Photorealistic AI automotive & concept reveal film crafted with custom diffusion pipelines and hyper-real texturing.',
    col1Image1: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=1000&q=85',
    col1Image2: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1000&q=85',
    col2Image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1400&q=85',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-futuristic-abstract-tunnel-with-glowing-lines-41584-large.mp4',
    mediaType: 'video',
    mediaItems: [
      {
        id: 'm-aiv2-1',
        type: 'video',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-futuristic-abstract-tunnel-with-glowing-lines-41584-large.mp4',
        poster: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1400&q=85',
        title: 'Hyperspeed Aerodynamic Flow',
      },
      {
        id: 'm-aiv2-2',
        type: 'video',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-circuit-board-with-glowing-signals-31910-large.mp4',
        poster: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=1000&q=85',
        title: 'Cockpit Telemetry Synthesis',
      },
      {
        id: 'm-aiv2-3',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1000&q=85',
        title: 'Cyberpunk Concept Silhouette',
        duration: 4,
      },
    ],
    liveUrl: 'https://youtube.com',
    techStack: ['Diffusion VFX', '16:9 & 9:16', 'Custom LoRA', 'Virtual Production'],
    featured: true,
  },
  // 03: WEBSITE BUILDING
  {
    id: 'web-01',
    number: '05',
    title: 'TrustAI Verification Hub',
    category: 'WEBSITE BUILDING',
    tagline: 'AI trust & verification platform engineered for high-security compliance and intelligent verification.',
    col1Image1: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1000&q=85',
    col1Image2: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1000&q=85',
    col2Image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1400&q=85',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-digital-animation-of-screens-with-charts-31911-large.mp4',
    mediaType: 'video',
    mediaItems: [
      {
        id: 'm-web1-1',
        type: 'video',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-digital-animation-of-screens-with-charts-31911-large.mp4',
        poster: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1400&q=85',
        title: 'Interactive Analytics & Verification UI',
      },
      {
        id: 'm-web1-2',
        type: 'video',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-server-room-with-racks-of-servers-and-cables-31518-large.mp4',
        poster: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1000&q=85',
        title: 'Distributed Identity Validation Mesh',
      },
      {
        id: 'm-web1-3',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1000&q=85',
        title: 'Zero-Trust Protocol Visualizer',
        duration: 4,
      },
    ],
    liveUrl: 'https://trustai.india.mesh.network',
    techStack: ['React', 'TypeScript', 'Tailwind', 'AI Verification API'],
    featured: true,
  },
  {
    id: 'web-02',
    number: '06',
    title: 'Luminex 3D Studio',
    category: 'WEBSITE BUILDING',
    tagline: 'Award-winning interactive brand experience with 3D WebGL scenes, fluid Lenis motion, and responsive performance.',
    col1Image1: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1000&q=85',
    col1Image2: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1000&q=85',
    col2Image: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=1400&q=85',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-digital-animation-of-screens-with-charts-31911-large.mp4',
    mediaType: 'video',
    mediaItems: [
      {
        id: 'm-web2-1',
        type: 'video',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-digital-animation-of-screens-with-charts-31911-large.mp4',
        poster: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=1400&q=85',
        title: '3D WebGL Interactive Architecture',
      },
      {
        id: 'm-web2-2',
        type: 'video',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-futuristic-abstract-tunnel-with-glowing-lines-41584-large.mp4',
        poster: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1000&q=85',
        title: 'Dynamic Lighting & Spatial Shader Canvas',
      },
      {
        id: 'm-web2-3',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1000&q=85',
        title: 'Responsive Mobile Fluid Canvas',
        duration: 4,
      },
    ],
    liveUrl: 'https://motionsites.ai',
    techStack: ['Three.js', 'Next.js', 'Framer Motion', 'Sub-second CDN'],
    featured: true,
  },
  // 04: AUTOMATION
  {
    id: 'aut-01',
    number: '07',
    title: 'RentOS AI Autonomous Flow',
    category: 'AUTOMATION',
    tagline: 'AI-powered rental management platform with automated lease processing and tenant intelligence.',
    col1Image1: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1000&q=85',
    col1Image2: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1000&q=85',
    col2Image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=85',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-server-room-with-racks-of-servers-and-cables-31518-large.mp4',
    mediaType: 'video',
    mediaItems: [
      {
        id: 'm-aut1-1',
        type: 'video',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-server-room-with-racks-of-servers-and-cables-31518-large.mp4',
        poster: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=85',
        title: 'Autonomous Multi-Agent Processing Pipeline',
      },
      {
        id: 'm-aut1-2',
        type: 'video',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-circuit-board-with-glowing-signals-31910-large.mp4',
        poster: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1000&q=85',
        title: 'Instant Automated Document Extraction',
      },
      {
        id: 'm-aut1-3',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1000&q=85',
        title: 'Tenant Intelligence Dashboard',
        duration: 4,
      },
    ],
    liveUrl: 'https://app.rentos.cloud',
    techStack: ['Full-Stack', 'Node.js', 'Vite', 'Agentic Automation'],
    featured: true,
  },
  {
    id: 'aut-02',
    number: '08',
    title: 'GovtJob Discovery Engine',
    category: 'AUTOMATION',
    tagline: 'Automated government-job discovery, eligibility analysis & intelligent application pipeline.',
    col1Image1: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=1000&q=85',
    col1Image2: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1000&q=85',
    col2Image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=85',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-circuit-board-with-glowing-signals-31910-large.mp4',
    mediaType: 'video',
    mediaItems: [
      {
        id: 'm-aut2-1',
        type: 'video',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-circuit-board-with-glowing-signals-31910-large.mp4',
        poster: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=85',
        title: 'Automated Scraping & Eligibility Parser',
      },
      {
        id: 'm-aut2-2',
        type: 'video',
        url: 'https://assets.mixkit.co/videos/preview/mixkit-server-room-with-racks-of-servers-and-cables-31518-large.mp4',
        poster: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=1000&q=85',
        title: 'Real-Time Notification & Auto-Dispatch',
      },
      {
        id: 'm-aut2-3',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1000&q=85',
        title: 'Application Tracking Telemetry',
        duration: 4,
      },
    ],
    liveUrl: 'https://stage.govtjob.engine.gov',
    techStack: ['Next.js', 'AI Extraction', 'Workflow Engine'],
    featured: true,
  },
];

export const initialWebsiteContent = {
  hero: {
    headline: 'AI BUILD',
    subtext: 'AI-POWERED EXPERIENCES & DIGITAL PRODUCTS FROM IDEA TO LAUNCH',
    badgeText: 'ai.build_',
    subBadge: 'Full-Stack & AI Agents',
    portraitUrl: 'https://shrug-person-78902957.figma.site/_components/v2/d24c01ad3a56fc65e942a1f501eb73db42d7cf9a/Rectangle_40443.81459862.png',
    portraitMediaType: 'image',
    portraitVideoUrl: '',
  },
  marquee: {
    row1Images: [
      'https://motionsites.ai/assets/hero-space-voyage-preview-eECLH3Yc.gif',
      'https://motionsites.ai/assets/hero-codenest-preview-Cgppc2qV.gif',
      'https://motionsites.ai/assets/hero-vex-ventures-preview-BczMFIiw.gif',
      'https://motionsites.ai/assets/hero-stellar-ai-v2-preview-DjvxjG3C.gif',
      'https://motionsites.ai/assets/hero-asme-preview-B_nGDnTP.gif',
      'https://motionsites.ai/assets/hero-transform-data-preview-Cx5OU29N.gif',
      'https://motionsites.ai/assets/hero-vitara-preview-Cjz2QYyU.gif',
      'https://motionsites.ai/assets/hero-terra-preview-BFjrCr7T.gif',
      'https://motionsites.ai/assets/hero-skyelite-preview-DHaZIgUv.gif',
      'https://motionsites.ai/assets/hero-aethera-preview-DknSlcTa.gif',
      'https://motionsites.ai/assets/hero-designpro-preview-D8c5_een.gif',
    ],
    row2Images: [
      'https://motionsites.ai/assets/hero-stellar-ai-preview-D3HL6bw1.gif',
      'https://motionsites.ai/assets/hero-xportfolio-preview-D4A8maiC.gif',
      'https://motionsites.ai/assets/hero-orbit-web3-preview-BXt4OttD.gif',
      'https://motionsites.ai/assets/hero-nexora-preview-cx5HmUgo.gif',
      'https://motionsites.ai/assets/hero-evr-ventures-preview-DZxeVFEX.gif',
      'https://motionsites.ai/assets/hero-planet-orbit-preview-DWAP8Z1P.gif',
      'https://motionsites.ai/assets/hero-new-era-preview-CocuDUm9.gif',
      'https://motionsites.ai/assets/hero-wealth-preview-B70idl_u.gif',
      'https://motionsites.ai/assets/hero-luminex-preview-CxOP7ce6.gif',
      'https://motionsites.ai/assets/hero-celestia-preview-0yO3jXO8.gif',
    ],
  },
  about: {
    heading: 'About',
    subPill: 'Studio Philosophy & Mission',
    bio: "AI Build is an AI-first digital studio that combines modern frontend engineering, bold design direction, and artificial intelligence to dramatically compress the distance between an ambitious idea and a production-ready digital product. Let's build something incredible together!",
    pillars: [
      {
        id: '1',
        title: 'AI Native',
        subtitle: 'Agentic Workflows',
        icon: 'cpu',
      },
      {
        id: '2',
        title: 'High Craft',
        subtitle: 'Tactile UI & Motion',
        icon: 'layers',
      },
      {
        id: '3',
        title: 'Velocity',
        subtitle: 'Idea to Launch',
        icon: 'zap',
      },
    ],
    decorativeAssets: {
      moonUrl: 'https://shrug-person-78902957.figma.site/_components/v2/ebb2b8f25d8e24d5f0a5ca8af4c950de81aa2fd7/moon_icon.11395d36.png',
      legoUrl: 'https://shrug-person-78902957.figma.site/_components/v2/ebb2b8f25d8e24d5f0a5ca8af4c950de81aa2fd7/lego_icon-1.703bb594.png',
      shapeUrl: 'https://shrug-person-78902957.figma.site/_components/v2/ebb2b8f25d8e24d5f0a5ca8af4c950de81aa2fd7/p59_1.4659672e.png',
      groupUrl: 'https://shrug-person-78902957.figma.site/_components/v2/ebb2b8f25d8e24d5f0a5ca8af4c950de81aa2fd7/Group_134-1.2e04f3ce.png',
    },
  },
  services: {
    heading: 'WHAT WE DO',
    subheading: 'We create. We build. We automate.',
    items: [
      {
        number: '01',
        title: 'UGC ADS',
        description: 'Ads people actually want to watch.',
        tagline: 'Performance-driven content that feels native to the feed.',
        videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-vertical-video-of-a-woman-showing-a-product-to-the-camera-43666-large.mp4',
        videoPoster: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
        mediaItems: [
          {
            id: 'm-ugc-1',
            type: 'video',
            url: 'https://assets.mixkit.co/videos/preview/mixkit-vertical-video-of-a-woman-showing-a-product-to-the-camera-43666-large.mp4',
            poster: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
            title: 'Creator Product Demonstration',
          },
          {
            id: 'm-ugc-2',
            type: 'video',
            url: 'https://assets.mixkit.co/videos/preview/mixkit-girl-doing-gymnastics-exercises-in-nature-41566-large.mp4',
            poster: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
            title: 'Dynamic Social Hook Creative',
          },
          {
            id: 'm-ugc-3',
            type: 'video',
            url: 'https://assets.mixkit.co/videos/preview/mixkit-vertical-video-of-a-woman-showing-a-product-to-the-camera-43666-large.mp4',
            poster: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
            title: 'High-Conversion Ad Reel',
          },
        ],
        weCreate: [
          'Product UGC',
          'Creator-style ads',
          'Hook variations',
          'Product demonstrations',
          'Testimonial-style creatives',
          'Paid social creatives',
        ],
        process: [
          'Brief',
          'Concept',
          'Script',
          'Storyboard',
          'Generate / Shoot',
          'Edit',
          'Variations',
        ],
        turnaround: '3–7 days',
        deliverables: [
          '9:16 vertical video',
          'Multiple hooks',
          'Multiple versions',
          'Ad-ready exports',
        ],
      },
      {
        number: '02',
        title: 'AI VIDEOS',
        description: 'Cinematic content, generated at the speed of an idea.',
        tagline: 'From a single idea to cinematic visual content built with AI.',
        videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-circuit-board-with-glowing-signals-31910-large.mp4',
        videoPoster: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1000&q=80',
        mediaItems: [
          {
            id: 'm-ai-1',
            type: 'video',
            url: 'https://assets.mixkit.co/videos/preview/mixkit-circuit-board-with-glowing-signals-31910-large.mp4',
            poster: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1000&q=80',
            title: 'AI Neural Pulse Cinema',
          },
          {
            id: 'm-ai-2',
            type: 'video',
            url: 'https://assets.mixkit.co/videos/preview/mixkit-futuristic-abstract-tunnel-with-glowing-lines-41584-large.mp4',
            poster: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=1000&q=80',
            title: 'Hyperspeed Latent Space Tunnel',
          },
          {
            id: 'm-ai-3',
            type: 'video',
            url: 'https://assets.mixkit.co/videos/preview/mixkit-circuit-board-with-glowing-signals-31910-large.mp4',
            poster: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1000&q=80',
            title: 'Generative Sci-Fi Sequences',
          },
        ],
        weCreate: [
          'Product films',
          'Cinematic ads',
          'AI commercials',
          'Social videos',
          'Brand films',
          'Concept visuals',
          'Motion sequences',
        ],
        process: [
          'Concept',
          'Visual Direction',
          'Storyboard',
          'Generation',
          'Editing',
          'Sound',
          'Final Master',
        ],
        turnaround: '3–10 days',
        deliverables: [
          '4K / 1080p',
          '9:16 · 16:9 · 1:1',
          'Social + campaign formats',
        ],
      },
      {
        number: '03',
        title: 'WEBSITE BUILDING',
        description: 'Websites that make your brand look expensive.',
        tagline: 'High-performance interactive websites engineered with modern React, motion, and AI integrations.',
        videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-digital-animation-of-screens-with-charts-31911-large.mp4',
        videoPoster: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1000&q=80',
        mediaItems: [
          {
            id: 'm-web-1',
            type: 'video',
            url: 'https://assets.mixkit.co/videos/preview/mixkit-digital-animation-of-screens-with-charts-31911-large.mp4',
            poster: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1000&q=80',
            title: 'Interactive Web Dashboard',
          },
          {
            id: 'm-web-2',
            type: 'video',
            url: 'https://assets.mixkit.co/videos/preview/mixkit-server-room-with-racks-of-servers-and-cables-31518-large.mp4',
            poster: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1000&q=80',
            title: 'Cloud Edge Infrastructure',
          },
          {
            id: 'm-web-3',
            type: 'video',
            url: 'https://assets.mixkit.co/videos/preview/mixkit-digital-animation-of-screens-with-charts-31911-large.mp4',
            poster: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1000&q=80',
            title: 'Responsive 3D Motion Prototype',
          },
        ],
        weCreate: [
          'Conversion landing pages',
          'Interactive Web3/AI web apps',
          'Custom headless CMS setups',
          'High-speed bespoke frontend',
          '3D & interactive animations',
          'Full-stack integrations',
        ],
        process: [
          'Discovery & Wireframing',
          'UI/UX Architecture',
          'Interactive Prototyping',
          'Production Codebase',
          'Speed & SEO Optimization',
          'Global CDN Deployment',
        ],
        turnaround: '1–3 weeks',
        deliverables: [
          'Production React / Next / Vite codebase',
          'Responsive mobile-first build',
          'Lighthouse 95+ performance',
          'Self-hosted CMS control',
        ],
      },
      {
        number: '04',
        title: 'AUTOMATIONS',
        description: 'Less repetitive work. More things getting done.',
        tagline: 'Intelligent multi-agent systems and custom workflows that run your operations automatically.',
        videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-server-room-with-racks-of-servers-and-cables-31518-large.mp4',
        videoPoster: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1000&q=80',
        mediaItems: [
          {
            id: 'm-auto-1',
            type: 'video',
            url: 'https://assets.mixkit.co/videos/preview/mixkit-server-room-with-racks-of-servers-and-cables-31518-large.mp4',
            poster: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1000&q=80',
            title: 'Distributed Compute Pipeline',
          },
          {
            id: 'm-auto-2',
            type: 'video',
            url: 'https://assets.mixkit.co/videos/preview/mixkit-circuit-board-with-glowing-signals-31910-large.mp4',
            poster: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1000&q=80',
            title: 'Autonomous Event Routing & Webhooks',
          },
          {
            id: 'm-auto-3',
            type: 'video',
            url: 'https://assets.mixkit.co/videos/preview/mixkit-server-room-with-racks-of-servers-and-cables-31518-large.mp4',
            poster: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1000&q=80',
            title: '24/7 Agent Telemetry & Self-Healing',
          },
        ],
        weCreate: [
          'Autonomous agent workflows',
          'CRM & pipeline synchronization',
          'LLM content & lead pipelines',
          'Custom API webhooks',
          'Customer support AI bots',
          'Internal ops tooling',
        ],
        process: [
          'Workflow Audit',
          'Architecture Blueprint',
          'Agent & API Pipeline Build',
          'Testing & Edge-case Handling',
          'Deployment & Monitoring',
          'Knowledge Base Sync',
        ],
        turnaround: '5–14 days',
        deliverables: [
          'End-to-end automated pipelines',
          'Real-time telemetry & alerts',
          'Documentation & training',
          'Zero-downtime failovers',
        ],
      },
    ],
  },
  contact: {
    email: 'hello@aibuild.studio',
    statusBadge: 'Studio Accepting Q3/Q4 Projects',
    ctaHeadline: "Let's Build",
    ctaSubtext: 'Have an AI product, bespoke web experience, or automated system to engineer? Let’s talk.',
  },
  characterLighting: {
    activePreset: 'studio-soft',
    customIntensity: 1.0,
    rimLightBoost: 1.0,
    enableSpecularHotspot: true,
    enableFresnelRim: true,
    enablePerformanceMode: true,
    performanceModeBehavior: 'adaptive',
  },
};

export const initialReviews = [
  {
    id: 'rev-1',
    author: 'Alexandre Renard',
    role: 'Founder & CEO',
    company: 'HyperQuant AI',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    rating: 5,
    comment: 'The speed and visual fidelity produced by AI Build is extraordinary. They turned our complex AI risk engine concept into a jaw-dropping web product in under 3 weeks.',
    date: 'August 24, 2026',
    status: 'approved',
    isFeatured: true,
    projectReferenced: 'TrustAI India',
  },
  {
    id: 'rev-2',
    author: 'Elena Rostova',
    role: 'Head of Product',
    company: 'Vanguard Zurich',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    rating: 5,
    comment: 'Flawless execution! The tactile feel, buttery smooth scroll physics, and custom design tokens exceeded every internal benchmark. Our clients love the portal.',
    date: 'August 18, 2026',
    status: 'approved',
    isFeatured: true,
    projectReferenced: 'RentOS AI',
  },
  {
    id: 'rev-3',
    author: 'Kenji Takahashi',
    role: 'Engineering Director',
    company: 'NeoTokyo Mesh',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    rating: 5,
    comment: 'Outstanding technical rigor. Their agentic pipeline and custom UI components delivered production-grade reliability on Day 1.',
    date: 'August 12, 2026',
    status: 'approved',
    isFeatured: true,
    projectReferenced: 'GovtJob Engine',
  },
  {
    id: 'rev-4',
    author: 'Sophia Chen',
    role: 'Design Principal',
    company: 'Aetheria Labs',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
    rating: 5,
    comment: 'True craftsmanship. The typography pairings and dark mode atmospheric glow make the entire product feel like luxury high-fashion hardware.',
    date: 'August 05, 2026',
    status: 'approved',
    isFeatured: true,
  },
  {
    id: 'rev-5',
    author: 'Marcus Vance',
    role: 'Managing Director',
    company: 'Summit Capital',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    rating: 4,
    comment: 'Very impressive turn-around time and crisp UI interactions. Looking forward to our next AI ecosystem launch with them.',
    date: 'July 29, 2026',
    status: 'approved',
    isFeatured: false,
  },
];

export const initialMessages = [
  {
    id: 'msg-1',
    name: 'Siddharth Rao',
    email: 'siddharth@hyperquant.ai',
    company: 'HyperQuant Technologies',
    projectType: '01 - AI Products & Autonomous Agents',
    budget: '$25,000 - $50,000+',
    message: 'We require a real-time autonomous financial agent with multi-modal voice processing and automated risk auditing.',
    date: 'Today at 10:45 AM',
    status: 'unread',
  },
  {
    id: 'msg-2',
    name: 'Marcus Vance',
    email: 'marcus@vanguardcapital.ch',
    company: 'Vanguard Private Equity Zurich',
    projectType: '03 - Intelligent Web & Mobile Ecosystems',
    budget: '$50,000+',
    message: 'Need a top-tier bespoke investor portal with institutional security, interactive charts, and live biometric signature flow.',
    date: 'Yesterday at 3:20 PM',
    status: 'read',
  },
  {
    id: 'msg-3',
    name: 'Clara Dupond',
    email: 'clara@lumiere-paris.fr',
    company: 'Lumière Studio Paris',
    projectType: '02 - Bespoke Digital Experiences',
    budget: '$15,000 - $25,000',
    message: 'Looking for a high-end luxury e-commerce experience with fluid motion, custom 3D web shaders, and seamless checkout.',
    date: 'Aug 28, 2026',
    status: 'replied',
  },
  {
    id: 'msg-4',
    name: 'Sarah Jenkins',
    email: 'sarah@beaconhealth.co',
    company: 'Beacon Health USA',
    projectType: '01 - AI Products & Autonomous Agents',
    budget: '$50,000+',
    message: 'HIPAA-compliant medical triage conversational assistant with real-time patient queue orchestration.',
    date: 'Aug 25, 2026',
    status: 'read',
  },
];

export const initialSavedQuotes = [
  {
    id: 'sq-101',
    clientName: 'Sarah Jenkins',
    clientEmail: 's.jenkins@nexusfintech.io',
    serviceCategory: '02 - AI VIDEOS',
    budgetRange: '$4,800 – $6,400',
    turnaroundTime: '6 – 9 Business Days',
    deliverables: [
      '3x 30s Cinematic AI Video Master(s)',
      'Bespoke Spatial Audio & Foley Soundscape',
      'Neural Voice Clone & Multilingual Dubbing',
      'Ad-Ready 4K Resolution & Multi-Aspect Exports',
    ],
    notes: 'For Series A launch campaign trailer across TikTok & YouTube.',
    createdAt: 'Aug 29, 2026',
    status: 'sent',
  },
  {
    id: 'sq-102',
    clientName: 'Marcus Vance',
    clientEmail: 'marcus@lumina.design',
    serviceCategory: '03 - WEBSITE & AUTOMATIONS',
    budgetRange: '$12,500 – $18,000',
    turnaroundTime: '12 – 18 Business Days',
    deliverables: [
      'Full-Stack React Web Application with Scalable Architecture',
      '3D WebGL / Interactive Canvas Experience',
      'Custom Owner CMS & Media Management Suite',
      'Cloud Database & Secure Multi-Role Auth',
    ],
    notes: 'Bespoke immersive portfolio and customer self-service portal.',
    createdAt: 'Aug 27, 2026',
    status: 'accepted',
  },
];

export const initialEstimatorSettings = {
  isEnabled: true,
  modalTitle: 'Scope Estimator & Pricing Simulator',
  modalSubtitle: 'Configure your project deliverables, assets, fidelity, and timeline to receive an instant commercial scope estimate.',
  rushSurchargePercentage: 25,
  categories: {
    ugcAds: {
      enabled: true,
      title: 'UGC Performance Ads',
      number: '01',
      basePriceAiPersona: 650,
      basePriceRealCreator: 1100,
      hookVariationPrice: 180,
      minAds: 1,
      maxAds: 12,
      defaultAdCount: 4,
      defaultHooks: 3,
    },
    aiVideo: {
      enabled: true,
      title: 'Cinematic AI & 3D Video',
      number: '02',
      basePriceCinematic: 1400,
      basePriceHyper3D: 2200,
      spatialAudioPricePerVideo: 350,
      voiceClonePricePerVideo: 250,
      minVideos: 1,
      maxVideos: 10,
      defaultVideoCount: 2,
    },
    webAutomation: {
      enabled: true,
      title: 'Web Platforms & AI Automation',
      number: '03',
      landingPagePriceMin: 3800,
      landingPagePriceMax: 6500,
      fullAppPriceMin: 7500,
      fullAppPriceMax: 14000,
      aiPipelinePriceMin: 9500,
      aiPipelinePriceMax: 18500,
      canvas3DAddonPrice: 1200,
      adminCmsAddonPrice: 800,
      databaseAuthAddonPrice: 1100,
    },
  },
};
